name: sholl-dashboard
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - streamlit
  - numpy
  - pandas
  - matplotlib
  - plotly
  - statsmodels
  - scikit-learn
  - scipy
  - shap
  - xgboost
  - numba
  - pillow
  - pip
  - pip:
    - streamlit-shap
